stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375/
  image: cr.yandex/yc/metadata-token-docker-helper:0.2
  services:
  - docker:19.03.1-dind
  script:
    - echo "build and push image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY/group1/crpsctg72feb8rmkng9p/hello:gitlab-$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/group1/crpsctg72feb8rmkng9p/hello:gitlab-$CI_COMMIT_SHORT_SHA